namespace Tests;

public class TestData
{
    public static readonly List<string> DoctorNames = new List<string>
    {
        "Dr. Ayesha Khan",
        "Dr. John Smith",
        "Dr. Priya Patel",
        "Dr. James Anderson",
        "Dr. Deepak Verma",
        "Dr. Rebecca Santos",
        "Dr. Ahmed Malik",
        "Dr. Emily Johnson",
        "Dr. Arjun Mehta",
        "Dr. Sarah Taylor",
        "Dr. Miguel Cruz",
        "Dr. Olivia Brown",
        "Dr. Haroon Qureshi",
        "Dr. Hannah White",
        "Dr. Rajeev Menon",
        "Dr. Jacob Thompson",
        "Dr. Anjali Desai",
        "Dr. Lauren Martin",
        "Dr. Rizwan Ahmed",
        "Dr. Ethan Walker",
        "Dr. Katrina Mendoza",
        "Dr. Charlotte Hall",
        "Dr. Naveed Iqbal",
        "Dr. Chloe Adams",
        "Dr. Rahul Sharma",
        "Dr. Grace Williams",
        "Dr. Benigno Reyes",
        "Dr. Sophie Harris",
        "Dr. Saira Raza",
        "Dr. Dylan Lewis",
        "Dr. Vinay Kapoor",
        "Dr. Ruby Green",
        "Dr. Manish Gupta",
        "Dr. Isabella Moore",
        "Dr. Javed Bashir",
        "Dr. Leo Robinson",
        "Dr. Harpreet Kaur",
        "Dr. Ava Campbell",
        "Dr. Kishore Nair",
        "Dr. Harry King",
        "Dr. Maureen Dela Cruz",
        "Dr. Natalie Young",
        "Dr. Zainab Mirza",
        "Dr. Patrick Evans",
        "Dr. Kavita Rao",
        "Dr. Lucy Wright",
        "Dr. Sajid Hussain",
        "Dr. Alexander Scott",
        "Dr. Pooja Joshi",
        "Dr. Ella Turner",
        "Dr. Farhan Siddiqui",
        "Dr. Benjamin Lee",
        "Dr. Anushka Reddy",
        "Dr. Zoe Cooper",
        "Dr. Imran Khalid",
        "Dr. Henry Clark",
        "Dr. Sneha Iyer",
        "Dr. Lily Carter",
        "Dr. Omar Jamil",
        "Dr. Jack Morris",
        "Dr. Grace Navarro",
        "Dr. Madison Hill",
        "Dr. Rakesh Prasad",
        "Dr. Adam Hughes",
        "Dr. Fatima Noor",
        "Dr. Amelia Parker",
        "Dr. Kartik Srinivasan",
        "Dr. Daniel Baker",
        "Dr. Leah Banzon",
        "Dr. George Mitchell",
        "Dr. Sanjay Kulkarni",
        "Dr. Thomas Reed",
        "Dr. Tasneem Haider",
        "Dr. Isabella James",
        "Dr. Anand Pillai",
        "Dr. Mason Phillips",
        "Dr. Laila Sabir",
        "Dr. Harper Bennett",
        "Dr. Nikhil Rathi",
        "Dr. Cooper Hayes",
        "Dr. Rohan Bhatt",
        "Dr. Zoe Jenkins",
        "Dr. Zahra Chaudhry",
        "Dr. Jackson Stewart",
        "Dr. Roshan Sethi",
        "Dr. Scarlett West",
        "Dr. Iqra Siddiqi",
        "Dr. Lachlan Woods",
        "Dr. Tanya Bedi",
        "Dr. Samuel Foster",
        "Dr. Afzal Rehman",
        "Dr. Audrey Simmons",
        "Dr. Kartika Devi",
        "Dr. Oliver Graham",
        "Dr. Jayant Mishra",
        "Dr. Victoria Bell",
        "Dr. Mariam Zafar",
        "Dr. William Brooks",
        "Dr. Parveen Khan",
        "Dr. Emma Russell"
    };

    public static readonly List<string> NormalNames = new List<string>
    {
        // Western Names
        "Michael Johnson",
        "Jennifer Smith",
        "Christopher Williams",
        "Elizabeth Brown",
        "Matthew Jones",
        "Jessica Miller",
        "David Garcia",
        "Sarah Davis",
        "Robert Rodriguez",
        "Ashley Martinez",
        "James Wilson",
        "Amanda Anderson",
        "John Taylor",
        "Stephanie Thomas",
        "Melissa Moore",
        "Daniel Martin",
        "Nicole Jackson",
        "Charles Thompson",
        "Katherine White",
        "Paul Lopez",
        "Samantha Lee",
        "Mark Harris",
        "Donald Lewis",
        "Lauren Robinson",
        "Steven Walker",
        "Laura Hall",
        "Kenneth Allen",
        "Emily Young",
        "Edward King",
        "Christina Wright",
        "Brian Scott",
        "Michelle Green",
        "George Adams",
        "Kimberly Baker",
        "Ronald Nelson",
        "Angela Mitchell",
        "Anthony Carter",
        "Lisa Perez",
        "Kevin Roberts",
        "Cynthia Turner",
        "Jason Phillips",
        "Deborah Campbell",
        "Timothy Parker",
        "Heather Evans",
        "Gary Edwards",
        "Amy Collins",
        "Stephen Stewart",
        "Karen Morris",

        // Eastern Asian Names
        "Wei Zhang",
        "Mei Li",
        "Hiroshi Tanaka",
        "Yuki Sato",
        "Jin-ho Kim",
        "Soo-jin Park",
        "Xiu Ying Chen",
        "Jian Wang",
        "Akira Suzuki",
        "Haruka Yamamoto",
        "Min-jun Choi",
        "Ji-young Lee",
        "Feng Liu",
        "Hui Yin Wu",
        "Takashi Watanabe",
        "Sakura Ito",
        "Seung-ho Kang",
        "Ji-woo Shin",
        "Xiao Huang",
        "Yan Zhou",
        "Daiki Nakamura",
        "Yumiko Kobayashi",
        "Dong-hyun Jung",
        "Mi-sook Yoon",
        "Jie Lin",
        "Na Zheng",
        "Kenji Ishikawa",
        "Aiko Matsumoto",
        "Hyun-woo Song",
        "Eun-ji Cho",

        // South Asian Names
        "Rajesh Kumar",
        "Priyanka Sharma",
        "Arjun Patel",
        "Sunita Singh",
        "Mohammed Rahman",
        "Fatima Begum",
        "Vikram Malhotra",
        "Ananya Chatterjee",
        "Abdul Karim",
        "Nusrat Jahan",
        "Sanjay Gupta",
        "Lakshmi Reddy",
        "Imran Khan",
        "Zara Ahmed",
        "Vijay Desai",
        "Meena Krishnan",
        "Tariq Mahmood",
        "Ayesha Malik",
        "Ram Chandra",
        "Divya Nair",
        "Salman Qureshi",
        "Deepika Mehta",
        "Hassan Ali",
        "Parvati Devi",
        "Prakash Iyer",
        "Neha Banerjee",
        "Faisal Siddiqui",
        "Reshma Biswas",
        "Rahul Joshi",
        "Sana Sheikh",

        // Middle Eastern Names
        "Ali Al-Mansour",
        "Leila Hakim",
        "Ahmed El-Masri",
        "Yasmin Karimi",
        "Omar Abboud",
        "Noor Al-Farsi",
        "Mustafa Khalil",
        "Mariam Shirazi",
        "Ibrahim Nasser",
        "Rania Haddad",
        "Youssef Kamal",
        "Amira Fahmy",
        "Hassan Qasim",
        "Sahar Zadeh",
        "Khalid Al-Sayed",
        "Zahra Najjar",
        "Mahmoud Saleh",
        "Dalia Khoury",
        "Rami Aziz",
        "Layla Husseini",

        // African Names
        "Kwame Osei",
        "Amara Diallo",
        "Oluwaseun Adeyemi",
        "Fatou Ndiaye",
        "Tendai Mutasa",
        "Nia Mandela",
        "Kofi Mensah",
        "Zainab Abdi",
        "Chidimma Okafor",
        "Abeba Tessema",
        "Sekou Traore",
        "Makena Wachira",
        "Babatunde Olawale",
        "Thabo Ndlovu",
        "Folami Owusu",
        "Ousmane Sow",
        "Nala Keita",
        "Chijioke Nwosu",
        "Maaza Bekele",

        // Hispanic/Latino Names
        "Carlos Hernandez",
        "Sofia Rodriguez",
        "Javier Gonzalez",
        "Isabella Lopez",
        "Alejandro Martinez",
        "Valentina Diaz",
        "Eduardo Morales",
        "Camila Torres",
        "Diego Ramirez",
        "Gabriela Sanchez",
        "Fernando Cruz",
        "Lucia Flores",
        "Antonio Reyes",
        "Carmen Ortiz",
        "Miguel Rivera",
        "Daniela Castro",
        "Ricardo Vargas",
        "Elena Gutierrez",
        "Manuel Jimenez",
        "Victoria Romero",

        // Special cases for transliteration testing
        "Sara Wilson",
        "Sarah Johnson",
        "Saira Khan",
        "Jaymes Peterson",
        "James Madison",
        "Jems Nichols",
        "Aisha Williams",
        "Eisha Roberts",
        "Mihel Fernandez",
        "Miguel Gomez",
        "Migel Castillo",
        "Jon Richardson",
        "John Hamilton",
        "Jhon Stevens",
        "Rebeka Watson",
        "Rebecca Morgan",
        "Rebeca Fisher",
        "Deepk Thomas",
        "Deepak Sharma",
        "Dipak Patel",
        "Haroon Malik",
        "Harun Ahmed",
        "Rajeef Menon",
        "Rajeev Kumar",
        "Rajev Singh",
        "Emly Bennett",
        "Emily Cooper",
        "Emmily Hayes",
        "Arjen Kapoor",
        "Arjun Mehta",
        "Arjoon Gupta"
    };
}