name: Build and Publish

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ArraySearch/ArraySearch.csproj

    - name: Build project
      run: dotnet build ArraySearch/ArraySearch.csproj --configuration Release --no-restore

    - name: Test project
      if: success()
      run: dotnet test Tests/Tests.csproj --no-build --verbosity normal

    - name: Pack project
      run: dotnet pack ArraySearch/ArraySearch.csproj --configuration Release --no-build -o ./nuget-packages
      
    - name: Publish to NuGet
      run: dotnet nuget push "./nuget-packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate