name: Build and Publish

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ArraySearch/ArraySearch.csproj

    - name: Build project
      run: dotnet build ArraySearch/ArraySearch.csproj --configuration Release --no-restore

    - name: Test project (if tests exist)
      if: success()
      run: dotnet test ArraySearch/ArraySearch.csproj --no-build --verbosity normal

  publish-nuget:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Pack project
        run: dotnet pack ArraySearch/ArraySearch.csproj --configuration Release --no-build -o ./nuget-packages

      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: ArraySearch.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
